# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"6\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"E\n\tUserReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2\xde\x01\n\x0bUserService\x12\x32\n\nCreateUser\x12\x12.hello.UserRequest\x1a\x10.hello.UserReply\x12\x31\n\x07GetUser\x12\x14.hello.UserIdRequest\x1a\x10.hello.UserReply\x12\x32\n\nUpdateUser\x12\x12.hello.UserRequest\x1a\x10.hello.UserReply\x12\x34\n\nDeleteUser\x12\x14.hello.UserIdRequest\x1a\x10.hello.UserReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=22
  _globals['_USERREQUEST']._serialized_end=76
  _globals['_USERIDREQUEST']._serialized_start=78
  _globals['_USERIDREQUEST']._serialized_end=105
  _globals['_USERREPLY']._serialized_start=107
  _globals['_USERREPLY']._serialized_end=176
  _globals['_USERSERVICE']._serialized_start=179
  _globals['_USERSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
